
const ERROR_CODES = {
  INVALID_DATE: 'INVALID_DATE',
  MISSING_FIELDS: 'MISSING_FIELDS',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  FLIGHT_NOT_FOUND: 'FLIGHT_NOT_FOUND',
  INVALID_ID: 'INVALID_ID',
  AUTH_FAILED: 'AUTH_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST'
};

module.exports = ERROR_CODES;

